---
name: Check pull request message format

on:
  workflow_call:

jobs:
  check-pr-title:
    name: Check pull request title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        timeout-minutes: 2
  
      - name: Checkout reusable actions repo
        uses: actions/checkout@v3
        with:
          repository: vyos/.github
          path: reusable-actions

      - name: Install the requests library
        run: pip3 install requests

      - name: Check the PR title
        id: check_pr_title
        timeout-minutes: 2
        run: |
          message=''
          output=$(./reusable-actions/scripts/check-pr-title-and-commit-messages.py '${{ github.event.pull_request.url }}' 2>&1 || true)
          if [ -n "$output" ]; then
            echo "$output"
            message="❌ PR Title / Commit Title does not follow the required format. ${output//$'\n'/. }"  
            exit 1
          else
            message="👍 No issues in PR Title / Commit Title"
          fi
          echo "message=$message" >> $GITHUB_OUTPUT
        shell: bash

      - name: Add PR comment
        if: always()
        uses: mshick/add-pr-comment@v2
        with:
          message: |-
            ${{ steps.check_pr_title.outputs.message }}
          allow-repeats: false
